### ISSUE TITLE
Create short names for clients

### ISSUE THREAD

**Issue by VictoriaMeldrum** [BallStateCBER/projects#5]
I want to have the formal names for each client/sponsor/partner listed in full as the actual tag, but in our left side navigation, I want to use short names with formal names appearing as a hint (easteregg?) when you roll over them.

The ability to edit the short name (nickname?) and the formal name should be found on this page: http://projects.cberdata.org/partners

**Comment by PhantomWatson** [comment]
Done! Short names have been set to be the same as the long names by default. The sidebar now only shows short names, with long names appearing if you hover your cursor over them. Short names can be edited via http://projects.cberdata.org/partners.
